# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "soundcloud"
name = "SoundCloud"
url = "https://soundcloud.com/alexander-philippov-dj"

[social.params]
icon = "brand-soundcloud"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com"

[social.params]
icon = "brand-twitter"
